const projects = [
  {
    id: 14,
    liveUrl: 'https://fipplusun.herokuapp.com/radios/70',
    name: 'Fip +1',
    stackFront: ['html', 'react', 'redux', 'styled components', 'css'],
    stackBack: ['node', 'express', 'herokuapp', 'sockets', 'mongo'],
    top: true,
    beginnerWarning: false,
  },
  {
    id: 1,
    codeUrl: 'https://github.com/Bauwi/node-redux-chat-app',
    liveUrl: 'https://react-node-chat-app.herokuapp.com/',
    name: 'Chat App',
    stackFront: ['html', 'react', 'redux', 'scss', 'css', 'react-router'],
    stackBack: ['mongo', 'node', 'express', 'sockets', 'herokuapp'],
    top: true,
    beginnerWarning: false,
  },
  {
    id: 2,
    codeUrl: 'https://github.com/Bauwi/blog-app',
    liveUrl: 'https://bloyster.herokuapp.com/',
    name: 'Blog App',
    stackFront: ['html', 'react', 'redux', 'scss', 'react-router'],
    stackBack: ['firebase', 'herokuapp'],
    top: true,
    beginnerWarning: false,
  },
  {
    id: 3,
    codeUrl: 'https://github.com/Bauwi/team-builder',
    liveUrl: 'https://line-me-up.herokuapp.com/',
    name: 'Team Builder',
    stackFront: ['html', 'react', 'redux', 'scss', 'css'],
    stackBack: ['node', 'express', 'herokuapp'],
    top: false,
    beginnerWarning: false,
  },
  {
    id: 13,
    codeUrl: 'https://github.com/Bauwi/team-builder-alt',
    liveUrl: '',
    name: 'Team Builder alt',
    stackFront: ['html', 'react', 'redux', 'scss', 'css'],
    stackBack: ['node', 'express', 'herokuapp'],
    top: false,
    beginnerWarning: false,
  },
  {
    id: 4,
    codeUrl: '',
    liveUrl: '',
    name: 'Portfolio',
    stackFront: ['html', 'react', 'gatsby', 'css'],
    stackBack: ['herokuapp'],
    top: false,
    beginnerWarning: false,
  },
  {
    id: 5,
    codeUrl: 'https://github.com/Bauwi/node-chat-app',
    liveUrl: 'https://node-chat-app-socket.herokuapp.com/',
    name: 'Chat App*',
    stackFront: ['html', 'jquery', 'scss'],
    stackBack: ['express', 'node', 'herokuapp', 'mongo'],
    top: false,
    beginnerWarning: false,
  },
  {
    id: 7,
    codeUrl: 'https://github.com/Bauwi/expensify-app',
    liveUrl: 'https://expenses-manager-kp.herokuapp.com/',
    name: 'Expansify App*',
    stackFront: ['html', 'react', 'redux', 'scss', 'css'],
    stackBack: ['firebase', 'herokuapp'],
    top: false,
    beginnerWarning: false,
  },
  {
    id: 6,
    codeUrl: 'https://github.com/Bauwi',
    liveUrl: '',
    name: 'Forum',
    stackFront: ['html', 'react', 'scss', 'css', 'react-router'],
    stackBack: ['mongo', 'meteor', 'herokuapp'],
    top: false,
    beginnerWarning: true,
  },
  {
    id: 8,
    codeUrl: '',
    liveUrl: 'https://codepen.io/Beauwie/pen/BREmjQ/',
    name: 'Tribute Page',
    stackFront: ['html', 'css', 'jquery'],
    stackBack: [],
    top: false,
    beginnerWarning: true,
  },
  {
    id: 9,
    codeUrl: '',
    liveUrl: 'https://codepen.io/Beauwie/pen/XgXaJr',
    name: 'Pomodoro',
    stackFront: ['html', 'css', 'jquery'],
    stackBack: [],
    top: false,
    beginnerWarning: true,
  },
  {
    id: 10,
    codeUrl: '',
    liveUrl: 'https://codepen.io/Beauwie/pen/yXNBOP',
    name: 'Calculator',
    stackFront: ['html', 'css', 'jquery'],
    stackBack: [],
    top: false,
    beginnerWarning: true,
  },
  {
    id: 11,
    codeUrl: 'https://github.com/Bauwi',
    liveUrl: 'https://github.com/Bauwi',
    name: 'Blog App2',
    stackFront: ['html', 'scss', 'jquery'],
    stackBack: ['firebase', 'herokuapp'],
    top: false,
    beginnerWarning: false,
  },
];

module.exports = {
  projects,
};
