const projects = [
  {
    id: 1,
    codeUrl: 'https://github.com/Bauwi',
    liveUrl: 'https://github.com/Bauwi',
    name: 'Chat App',
    stackFront: ['html', 'react', 'redux', 'scss', 'css', 'react-router'],
    stackBack: ['mongo', 'node', 'express', 'sockets', 'herokuapp'],
    top: true,
  },
  {
    id: 2,
    codeUrl: 'https://github.com/Bauwi',
    liveUrl: 'https://github.com/Bauwi',
    name: 'Blog App',
    stackFront: ['html', 'react', 'redux', 'scss', 'react-router'],
    stackBack: ['firebase', 'herokuapp'],
    top: true,
  },
  {
    id: 3,
    codeUrl: 'https://github.com/Bauwi',
    liveUrl: 'https://github.com/Bauwi',
    name: 'Chat App',
    stackFront: ['html', 'react', 'redux', 'scss', 'css', 'jquery'],
    stackBack: ['mongo', 'node', 'express', 'herokuapp'],
    top: true,
  },
  {
    id: 4,
    codeUrl: 'https://github.com/Bauwi',
    liveUrl: 'https://github.com/Bauwi',
    name: 'Chat App2',
    stackFront: ['html', 'react', 'redux', 'scss', 'css', 'jquery'],
    stackBack: ['mongo', 'node', 'herokuapp'],
    top: false,
  },
  {
    id: 5,
    codeUrl: 'https://github.com/Bauwi',
    liveUrl: 'https://github.com/Bauwi',
    name: 'Blog App2',
    stackFront: ['html', 'react', 'redux', 'scss'],
    stackBack: ['firebase', 'herokuapp'],
    top: false,
  },
  {
    id: 6,
    codeUrl: 'https://github.com/Bauwi',
    liveUrl: 'https://github.com/Bauwi',
    name: 'Chat App2',
    stackFront: ['html', 'react', 'redux', 'scss', 'css', 'jquery'],
    stackBack: ['mongo', 'node', 'express', 'sockets', 'herokuapp', 'mongoose'],
    top: false,
  },
  {
    id: 7,
    codeUrl: 'https://github.com/Bauwi',
    liveUrl: 'https://github.com/Bauwi',
    name: 'Chat App2',
    stackFront: ['html', 'react', 'redux', 'scss', 'css'],
    stackBack: ['mongo', 'node', 'express', 'sockets', 'herokuapp, mongoose'],
    top: false,
  },
  {
    id: 8,
    codeUrl: 'https://github.com/Bauwi',
    liveUrl: 'https://github.com/Bauwi',
    name: 'Blog App2',
    stackFront: ['html', 'react', 'redux', 'scss', 'react-router'],
    stackBack: ['firebase', 'herokuapp, meteor'],
    top: false,
  },
  {
    id: 9,
    codeUrl: 'https://github.com/Bauwi',
    liveUrl: 'https://github.com/Bauwi',
    name: 'Chat App2',
    stackFront: ['html', 'react', 'redux', 'scss', 'css', 'react-router'],
    stackBack: ['mongo', 'node', 'express', 'sockets', 'herokuapp', 'mongoose'],
    top: false,
  },
  {
    id: 10,
    codeUrl: 'https://github.com/Bauwi',
    liveUrl: 'https://github.com/Bauwi',
    name: 'Chat App2',
    stackFront: ['html', 'react', 'redux', 'scss', 'css'],
    stackBack: ['mongo', 'node', 'express', 'sockets', 'herokuapp'],
    top: false,
  },
  {
    id: 11,
    codeUrl: 'https://github.com/Bauwi',
    liveUrl: 'https://github.com/Bauwi',
    name: 'Blog App2',
    stackFront: ['html', 'scss', 'jquery'],
    stackBack: ['firebase', 'herokuapp'],
    top: false,
  },
];

module.exports = {
  projects,
};
